### ISSUE TITLE
Which convention to use?

### ISSUE THREAD

**Issue by Joshuaalbert** [ratt-ru/codex-africanus#302]
@sjperkins (or whomever sees this) I'm looking to understand somethings:

1. Who uses which convention for RIME. 

![CodeCogsEqn](https://github.com/ratt-ru/codex-africanus/assets/14807032/b4dd90d0-0a28-4d07-889a-b94afcd017d1)

I think at least WSClean uses so-called casa convention, with + in exponent. More importantly, which convention should I be using when?

2. Also, in what cases does getting the convention right matter? 

The conventions are related by a single quick op, since `V(-u,-v,-w) = conj(V(u,v,w))`.

Clearly, if you calibrate off a sky-model with wrong convention this is the same as trying to minimise `|V - conj(V)|^2 = 2 Im(V)^2` since `a + i b - (a - i b) = 2 i b`. So you'll totally ignore the real components.

What about imaging? Since we only store V and use the knowledge that V is Hermitian, would the image be the same regardless of convention?

**Comment by sjperkins** [comment]
The decision as to which convention to use devolves to the application, which by and large will choose CASA for compatibility reasons. For example, in Quartical and pfb-clean:

- https://github.com/ratt-ru/QuartiCal/blob/09829908551ce18211e546a9053023c50b5bce7b/quartical/config/argument_schema.yaml#L146
- https://github.com/ratt-ru/pfb-clean/blob/f92d026ae27d9ab009c1ffe78b409ad6b62ab53e/pfb/operators/gridder.py#L306

**Comment by Joshuaalbert** [comment]
Thanks! Seems like a good approach to write all implementations in terms of Fourier and then just take complex conj after if convention should be CASA. Then at least internally it matches physics conventions, and it's only a single op to convert.
